version: '3.7'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./server/.env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: beer-db
